# Generated by Django 5.1.4 on 2025-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_delivery_date_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='products',
            field=models.ManyToManyField(related_name='months', to='contact.product'),
        ),
    ]
