# Generated by Django 5.1.4 on 2025-01-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_month_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
