# Generated by Django 5.1.4 on 2025-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
