# Generated by Django 5.1.4 on 2025-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_farmerprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='farmer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
