# Generated by Django 5.1.4 on 2025-01-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_farmerprofile_rating_farmer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
